export const idealWeightCalculatorContent = {
  slug: { pt: "calculadora-peso-ideal" },
  title: { pt: "Calculadora de Peso Ideal" },
  description: { pt: "Calcule uma faixa estimada de peso ideal com base na sua altura." },
  seo: {
    title: { pt: "Calculadora de Peso Ideal - Faixa Saudável por Altura" },
    description: { pt: "Descubra uma faixa estimada de peso ideal usando altura, IMC de referência e visual claro." },
  },
  article: [
    { heading: { pt: "O Que é Peso Ideal?" }, body: { pt: "Peso ideal é uma faixa estimada de peso corporal associada a referências populacionais de IMC para determinada altura." } },
    { heading: { pt: "Como a Faixa é Calculada" }, body: { pt: "Esta calculadora usa a faixa de IMC de referência entre 18,5 e 24,9 para estimar peso mínimo, máximo e um ponto central." } },
    { heading: { pt: "Peso Ideal Não é Diagnóstico" }, body: { pt: "A faixa serve como orientação geral. Composição corporal, massa muscular, idade, sexo e histórico de saúde também importam." } },
    { heading: { pt: "Exemplo Prático" }, body: { pt: "Para uma altura de 175 cm, a faixa estimada fica aproximadamente entre 56,7 kg e 76,3 kg." } },
    { heading: { pt: "Como Usar Esta Calculadora" }, body: { pt: "Informe sua altura em centímetros. Se quiser comparar com seu peso atual, use o perfil fitness completo." } },
  ],
  faq: [
    { question: { pt: "Qual é meu peso ideal?" }, answer: { pt: "Depende de altura, composição corporal e contexto individual. A calculadora mostra uma faixa estimada." } },
    { question: { pt: "A faixa de peso ideal é exata?" }, answer: { pt: "Não. Ela é uma referência geral baseada em IMC, não uma avaliação médica individual." } },
    { question: { pt: "Músculos alteram o peso ideal?" }, answer: { pt: "Sim. Pessoas com mais massa muscular podem ficar acima da faixa sem que isso represente necessariamente pior condição física." } },
    { question: { pt: "Esta calculadora substitui orientação profissional?" }, answer: { pt: "Não. Ela fornece uma estimativa geral e não substitui orientação médica, nutricional ou física." } },
  ],
  formula: {
    expression: { pt: "Peso ideal = altura² × IMC 18,5 a 24,9" },
    explanation: { pt: "A altura é convertida para metros. O peso mínimo usa IMC 18,5, o máximo usa 24,9 e o alvo visual usa um ponto central estimado." },
  },
  ui: {
    heading: { pt: "Calculadora de Peso Ideal" },
    helper: { pt: "Veja uma faixa estimada de peso para sua altura." },
    height: { pt: "Altura (cm)" },
    idealWeight: { pt: "Peso ideal" },
    resultTitle: { pt: "Sua faixa estimada" },
    status: { pt: "Referência visual" },
    minTarget: { pt: "Mínimo estimado" },
    centerTarget: { pt: "Ponto central" },
    maxTarget: { pt: "Máximo estimado" },
    resultHelper: { pt: "Use esta faixa como referência, não como diagnóstico. O próximo passo é comparar com IMC, calorias, água, proteína e progresso." },
    openFitness: { pt: "Gerar meu perfil fitness completo" },
    ctaEyebrow: { pt: "Próximo passo" },
    ctaTitle: { pt: "Descubra também:" },
    ctaDescription: { pt: "Veja peso ideal junto com IMC, calorias, metabolismo, água e proteína dentro do NexTool Fit." },
    bmi: { pt: "IMC" },
    calories: { pt: "Calorias diárias" },
    metabolism: { pt: "Metabolismo basal" },
    protein: { pt: "Proteína diária" },
    disclaimer: { pt: "Esta é uma estimativa geral para adultos e não substitui orientação médica, nutricional ou física." },
  },
};
