export const idealWeightCalculatorContent = {
  slug: { en: "ideal-weight-calculator" },
  title: { en: "Ideal Weight Calculator" },
  description: { en: "Calculate an estimated ideal weight range based on your height." },
  seo: {
    title: { en: "Ideal Weight Calculator - Healthy Weight Range by Height" },
    description: { en: "Estimate an ideal weight range using height, BMI reference values and a clear visual result." },
  },
  article: [
    { heading: { en: "What Is Ideal Weight?" }, body: { en: "Ideal weight is an estimated body-weight range associated with population BMI references for a given height." } },
    { heading: { en: "How the Range Is Calculated" }, body: { en: "This calculator uses a BMI reference range from 18.5 to 24.9 to estimate minimum, maximum and center weights." } },
    { heading: { en: "Ideal Weight Is Not a Diagnosis" }, body: { en: "The range is general guidance. Body composition, muscle mass, age, sex and health history also matter." } },
    { heading: { en: "Practical Example" }, body: { en: "For a height of 5 ft 10 in, the estimated range is about 128.9 lb to 173.5 lb." } },
    { heading: { en: "Using This Calculator" }, body: { en: "Enter height in feet and inches. To compare with current weight, use the full fitness profile." } },
  ],
  faq: [
    { question: { en: "What is my ideal weight?" }, answer: { en: "It depends on height, body composition and personal context. The calculator shows an estimated range." } },
    { question: { en: "Is the ideal weight range exact?" }, answer: { en: "No. It is a general BMI-based reference, not an individual medical assessment." } },
    { question: { en: "Can muscle change ideal weight?" }, answer: { en: "Yes. People with more muscle may weigh above the range without that necessarily meaning worse fitness." } },
    { question: { en: "Does this replace professional advice?" }, answer: { en: "No. This is a general estimate and does not replace medical, nutrition or fitness advice." } },
  ],
  formula: {
    expression: { en: "Ideal weight = height² × BMI 18.5 to 24.9" },
    explanation: { en: "English inputs use feet and inches, converted internally before estimating the BMI-based weight range." },
  },
  ui: {
    heading: { en: "Ideal Weight Calculator" },
    helper: { en: "See an estimated weight range for your height." },
    height: { en: "Height" },
    heightFt: { en: "Height (ft)" },
    heightIn: { en: "Height (in)" },
    idealWeight: { en: "Ideal weight" },
    resultTitle: { en: "Your estimated range" },
    status: { en: "Visual reference" },
    minTarget: { en: "Estimated minimum" },
    centerTarget: { en: "Center point" },
    maxTarget: { en: "Estimated maximum" },
    resultHelper: { en: "Use this range as a reference, not a diagnosis. The next step is comparing it with BMI, calories, water, protein and progress." },
    openFitness: { en: "Generate my full fitness profile" },
    ctaEyebrow: { en: "Next step" },
    ctaTitle: { en: "Also discover:" },
    ctaDescription: { en: "See ideal weight together with BMI, calories, metabolism, water and protein inside NexTool Fit." },
    bmi: { en: "BMI" },
    calories: { en: "Daily calories" },
    metabolism: { en: "Basal metabolism" },
    protein: { en: "Daily protein" },
    disclaimer: { en: "This is a general estimate for adults and does not replace medical, nutrition or fitness advice." },
  },
};
