export const proteinCalculatorContent = {
  slug: { en: "protein-calculator" },
  title: { en: "Daily Protein Calculator" },
  description: { en: "Calculate an estimated daily protein range based on body weight and fitness goal." },
  seo: {
    title: { en: "Protein Calculator - Daily Protein Intake in Grams" },
    description: { en: "Estimate how many grams of protein per day you may need for fat loss, maintenance or muscle gain." },
  },
  article: [
    { heading: { en: "What Is a Protein Calculator?" }, body: { en: "A protein calculator estimates a daily protein range based on body weight and fitness goal." } },
    { heading: { en: "Why Protein Matters" }, body: { en: "Protein supports lean mass, muscle recovery and satiety as part of a balanced nutrition plan." } },
    { heading: { en: "Protein for Fat Loss" }, body: { en: "During fat loss, adequate protein can help preserve lean mass while calories are adjusted." } },
    { heading: { en: "Protein for Muscle Gain" }, body: { en: "For muscle gain, protein works best alongside training, enough calories and recovery." } },
    { heading: { en: "Practical Example" }, body: { en: "A 180 lb person may use an approximate range of 131 g to 180 g per day when focusing on muscle gain." } },
    { heading: { en: "Using This Protein Calculator" }, body: { en: "Enter your weight in pounds and choose a goal. The calculator converts pounds internally and estimates a practical daily protein range." } },
  ],
  faq: [
    { question: { en: "How much protein should I eat per day?" }, answer: { en: "It depends on weight, goal, training and nutrition context. This calculator gives an estimated range." } },
    { question: { en: "Can protein help with weight loss?" }, answer: { en: "Protein can support satiety and lean mass, but weight loss still depends on the overall energy balance." } },
    { question: { en: "Do I need to hit protein every day?" }, answer: { en: "Weekly consistency matters, but a daily target makes tracking easier." } },
    { question: { en: "Does this replace nutrition advice?" }, answer: { en: "No. This is a general estimate and does not replace medical or nutrition advice." } },
  ],
  formula: {
    expression: { en: "Daily protein = Body weight (kg) × 1.2 to 2.2 g" },
    explanation: { en: "English inputs use pounds, then convert pounds to kilograms before applying goal-based protein multipliers." },
  },
  ui: {
    heading: { en: "Daily Protein Calculator" },
    helper: { en: "Estimate how many grams of protein to eat per day." },
    weight: { en: "Weight (lb)" },
    goal: { en: "Goal" },
    lose: { en: "Fat loss" },
    maintain: { en: "Maintain weight" },
    gain: { en: "Muscle gain" },
    protein: { en: "Daily protein" },
    resultTitle: { en: "Your daily range" },
    status: { en: "Daily estimate" },
    minTarget: { en: "Practical minimum" },
    maxTarget: { en: "Upper range" },
    resultHelper: { en: "This range estimates how much protein to eat per day to support satiety, recovery and muscle mass. Start with the practical minimum and adjust based on routine, training, calories and food preferences." },
    openFitness: { en: "Generate my full fitness profile" },
    ctaEyebrow: { en: "Next step" },
    ctaTitle: { en: "Also discover:" },
    ctaDescription: { en: "See protein together with BMI, calories, water and metabolism inside NexTool Fit." },
    calories: { en: "Daily calories" },
    metabolism: { en: "Basal metabolism" },
    water: { en: "Daily water" },
    idealWeight: { en: "Ideal weight" },
    disclaimer: { en: "This is a general estimate for adults and does not replace medical or nutrition advice." },
  },
};
