export const proteinCalculatorContent = {
  slug: { pt: "calculadora-de-proteina" },
  title: { pt: "Calculadora de Proteína Diária" },
  description: { pt: "Calcule uma faixa estimada de proteína por dia com base no peso corporal e objetivo fitness." },
  seo: {
    title: { pt: "Calculadora de Proteína Diária - Gramas de Proteína por Dia" },
    description: { pt: "Descubra quantos gramas de proteína consumir por dia para perder gordura, manter peso ou ganhar massa muscular." },
  },
  article: [
    { heading: { pt: "O Que é uma Calculadora de Proteína?" }, body: { pt: "Uma calculadora de proteína estima uma faixa diária de gramas de proteína com base no peso corporal e no objetivo fitness." } },
    { heading: { pt: "Por Que a Proteína Importa" }, body: { pt: "A proteína ajuda na manutenção de massa magra, recuperação muscular e saciedade dentro de uma rotina alimentar equilibrada." } },
    { heading: { pt: "Proteína Para Perder Gordura" }, body: { pt: "Em uma fase de perda de gordura, uma ingestão adequada de proteína pode ajudar a preservar massa magra enquanto as calorias são ajustadas." } },
    { heading: { pt: "Proteína Para Ganhar Massa" }, body: { pt: "Para ganho de massa, a proteína precisa trabalhar junto com treino, calorias suficientes e descanso." } },
    { heading: { pt: "Exemplo Prático" }, body: { pt: "Uma pessoa com 70 kg pode usar uma faixa aproximada de 112 g a 154 g por dia, dependendo do objetivo escolhido." } },
    { heading: { pt: "Como Usar Esta Calculadora" }, body: { pt: "Informe seu peso e escolha o objetivo. Use o resultado como estimativa inicial e ajuste com acompanhamento profissional quando necessário." } },
  ],
  faq: [
    { question: { pt: "Quanta proteína devo consumir por dia?" }, answer: { pt: "Depende do peso, objetivo, treino e contexto alimentar. A calculadora mostra uma faixa estimada." } },
    { question: { pt: "Proteína ajuda a emagrecer?" }, answer: { pt: "Ela pode ajudar na saciedade e preservação de massa magra, mas o emagrecimento depende do conjunto da dieta e gasto energético." } },
    { question: { pt: "Preciso bater proteína todos os dias?" }, answer: { pt: "Consistência semanal costuma ser mais importante que perfeição diária, mas uma meta diária ajuda no acompanhamento." } },
    { question: { pt: "A calculadora substitui nutricionista?" }, answer: { pt: "Não. Ela fornece uma estimativa geral e não substitui orientação médica ou nutricional." } },
  ],
  formula: {
    expression: { pt: "Proteína diária = Peso (kg) × 1,2 a 2,2 g" },
    explanation: { pt: "A faixa muda conforme o objetivo: manutenção usa uma faixa menor; perda de gordura e ganho de massa usam faixas mais altas." },
  },
  ui: {
    heading: { pt: "Calculadora de Proteína Diária" },
    helper: { pt: "Estime quantos gramas de proteína consumir por dia." },
    weight: { pt: "Peso (kg)" },
    goal: { pt: "Objetivo" },
    lose: { pt: "Perder gordura" },
    maintain: { pt: "Manter peso" },
    gain: { pt: "Ganhar massa" },
    protein: { pt: "Proteína diária" },
    resultTitle: { pt: "Sua faixa diária" },
    status: { pt: "Estimativa diária" },
    minTarget: { pt: "Mínimo prático" },
    maxTarget: { pt: "Faixa superior" },
    resultHelper: { pt: "Esta faixa estima quanta proteína consumir por dia para apoiar saciedade, recuperação e massa muscular. Comece pelo mínimo prático e ajuste conforme rotina, treino, calorias e preferência alimentar." },
    openFitness: { pt: "Gerar meu perfil fitness completo" },
    ctaEyebrow: { pt: "Próximo passo" },
    ctaTitle: { pt: "Descubra também:" },
    ctaDescription: { pt: "Veja proteína junto com IMC, calorias, água e metabolismo dentro do NexTool Fit." },
    calories: { pt: "Calorias diárias" },
    metabolism: { pt: "Metabolismo basal" },
    water: { pt: "Água diária" },
    idealWeight: { pt: "Peso ideal" },
    disclaimer: { pt: "Esta é uma estimativa geral para adultos e não substitui orientação médica ou nutricional." },
  },
};
