export const macroCalculatorContent = {
  slug: { pt: "calculadora-de-macros" },
  title: { pt: "Calculadora de Macros" },
  description: { pt: "Distribua suas calorias diárias em proteína, carboidratos e gorduras com base no peso e objetivo." },
  seo: {
    title: { pt: "Calculadora de Macros - Proteína, Carboidratos e Gorduras" },
    description: { pt: "Calcule uma divisão estimada de macronutrientes por dia para perda de gordura, manutenção ou ganho de massa." },
  },
  article: [
    { heading: { pt: "O Que São Macros?" }, body: { pt: "Macros são os macronutrientes que fornecem energia: proteína, carboidratos e gorduras. A divisão entre eles ajuda a transformar calorias em um plano alimentar mais prático." } },
    { heading: { pt: "Como Esta Calculadora Funciona" }, body: { pt: "A calculadora usa suas calorias diárias, peso corporal e objetivo para estimar gramas de proteína, gordura e carboidratos por dia." } },
    { heading: { pt: "Proteína, Gordura e Carboidrato" }, body: { pt: "Proteína ajuda na saciedade e manutenção muscular, gorduras apoiam funções corporais e carboidratos completam a energia restante do dia." } },
    { heading: { pt: "Exemplo Prático" }, body: { pt: "Uma pessoa com 70 kg, meta de manutenção e 2.517 kcal/dia pode receber uma divisão aproximada de 105 g de proteína, 84 g de gordura e 335 g de carboidratos." } },
    { heading: { pt: "Use Como Estimativa" }, body: { pt: "A divisão ideal pode mudar conforme treino, rotina, preferências alimentares e orientação profissional. Use o resultado como ponto de partida ajustável." } },
  ],
  faq: [
    { question: { pt: "O que é uma calculadora de macros?" }, answer: { pt: "É uma ferramenta que distribui calorias diárias entre proteína, carboidratos e gorduras." } },
    { question: { pt: "Preciso contar macros todos os dias?" }, answer: { pt: "Não necessariamente. Muitas pessoas usam macros por períodos específicos para entender melhor a alimentação." } },
    { question: { pt: "Macros substituem nutricionista?" }, answer: { pt: "Não. O resultado é uma estimativa geral e não substitui acompanhamento profissional." } },
    { question: { pt: "Por que carboidratos mudam tanto?" }, answer: { pt: "Porque eles recebem as calorias restantes depois de estimar proteína e gordura." } },
  ],
  formula: {
    expression: { pt: "Proteína = faixa por peso e objetivo; Gorduras = 25–30% das calorias; Carboidratos = calorias restantes" },
    explanation: { pt: "Proteína e carboidratos usam 4 kcal por grama. Gorduras usam 9 kcal por grama. O peso em kg ajuda a estimar a proteína diária." },
  },
  ui: {
    heading: { pt: "Calculadora de Macros" },
    helper: { pt: "Transforme calorias diárias em proteína, carboidratos e gorduras." },
    calories: { pt: "Calorias por dia" },
    weight: { pt: "Peso (kg)" },
    goal: { pt: "Objetivo" },
    lose: { pt: "Perder gordura" },
    maintain: { pt: "Manter peso" },
    gain: { pt: "Ganhar massa" },
    resultTitle: { pt: "Divisão diária" },
    status: { pt: "Macros estimados" },
    protein: { pt: "Proteína" },
    carbs: { pt: "Carboidratos" },
    fat: { pt: "Gorduras" },
    caloriesLabel: { pt: "Calorias" },
    resultHelper: { pt: "Use como ponto de partida e ajuste conforme treino, fome, rotina e orientação profissional." },
    ctaEyebrow: { pt: "Próximo passo" },
    ctaTitle: { pt: "Descubra também:" },
    bmi: { pt: "IMC" },
    bodyFat: { pt: "Gordura corporal" },
    water: { pt: "Água diária" },
    idealWeight: { pt: "Peso ideal" },
    openFitness: { pt: "Gerar meu perfil fitness completo" },
    ctaDescription: { pt: "Veja seus macros junto com IMC, peso ideal, água, proteína e evolução dentro do NexTool Fit." },
    disclaimer: { pt: "Estimativa geral para adultos. Não substitui plano alimentar individualizado ou orientação profissional." },
  },
};
