export const macroCalculatorContent = {
  slug: { en: "macro-calculator" },
  title: { en: "Macro Calculator" },
  description: { en: "Split your daily calories into protein, carbs and fats based on weight and fitness goal." },
  seo: {
    title: { en: "Macro Calculator - Protein, Carbs and Fat Per Day" },
    description: { en: "Calculate an estimated daily macro split for fat loss, maintenance or muscle gain." },
  },
  article: [
    { heading: { en: "What Are Macros?" }, body: { en: "Macros are the nutrients that provide calories: protein, carbohydrates and fats. A macro split turns a daily calorie target into practical gram amounts." } },
    { heading: { en: "How This Calculator Works" }, body: { en: "The calculator uses your daily calories, Weight (lb) and fitness goal to estimate grams of protein, fat and carbs per day." } },
    { heading: { en: "Protein, Fat and Carbs" }, body: { en: "Protein supports satiety and muscle maintenance, fats support normal body functions, and carbs receive the remaining daily calories." } },
    { heading: { en: "Practical Example" }, body: { en: "Someone at 180 lb, maintenance goal and 2,724 kcal/day may receive an estimated split near 122 g protein, 91 g fat and 354 g carbs." } },
    { heading: { en: "Use It as an Estimate" }, body: { en: "Macro targets can change with training, appetite, food preferences and professional guidance. Use this as an adjustable starting point." } },
  ],
  faq: [
    { question: { en: "What is a macro calculator?" }, answer: { en: "It splits daily calories between protein, carbohydrates and fats." } },
    { question: { en: "Do I need to track macros every day?" }, answer: { en: "Not necessarily. Many people use macros for specific periods to understand food intake better." } },
    { question: { en: "Do macros replace a nutrition professional?" }, answer: { en: "No. This is a general estimate and does not replace personalized nutrition guidance." } },
    { question: { en: "Why do carbs change so much?" }, answer: { en: "Carbs receive the remaining calories after protein and fat are estimated." } },
  ],
  formula: {
    expression: { en: "Protein = weight and goal range; Fat = 25–30% of calories; Carbs = remaining calories" },
    explanation: { en: "Protein and carbs use 4 kcal per gram. Fat uses 9 kcal per gram. Weight (lb) is converted internally before estimating daily protein." },
  },
  ui: {
    heading: { en: "Macro Calculator" },
    helper: { en: "Turn daily calories into protein, carbs and fats." },
    calories: { en: "Calories per day" },
    weight: { en: "Weight (lb)" },
    goal: { en: "Goal" },
    lose: { en: "Fat loss" },
    maintain: { en: "Maintain weight" },
    gain: { en: "Muscle gain" },
    resultTitle: { en: "Daily split" },
    status: { en: "Estimated macros" },
    protein: { en: "Protein" },
    carbs: { en: "Carbs" },
    fat: { en: "Fat" },
    caloriesLabel: { en: "Calories" },
    resultHelper: { en: "Use this as a starting point and adjust based on training, hunger, schedule and professional guidance." },
    ctaEyebrow: { en: "Next step" },
    ctaTitle: { en: "Also discover:" },
    bmi: { en: "BMI" },
    bodyFat: { en: "Body fat" },
    water: { en: "Daily water" },
    idealWeight: { en: "Ideal weight" },
    openFitness: { en: "Generate my full fitness profile" },
    ctaDescription: { en: "See your macros together with BMI, ideal weight, water, protein and progress inside NexTool Fit." },
    disclaimer: { en: "General adult estimate. This does not replace a personalized nutrition plan or professional guidance." },
  },
};
